import { Transaction } from "../transactions.types";

export default [
  {
    type: "transactions",
    id: "2",
    attributes: {
      created_at: "2018-09-17T12:46:47+01:00",
      updated_at: "2018-09-17T12:46:47+01:00",
      user: "3",
      group_title: "Split transaction title.",
      transactions: [
        {
          user: "3",
          transaction_journal_id: "10421",
          type: "withdrawal",
          date: "2018-09-17T12:46:47+01:00",
          order: 0,
          currency_id: "12",
          currency_code: "EUR",
          currency_symbol: "$",
          currency_name: "Euro",
          currency_decimal_places: 2,
          foreign_currency_id: "17",
          foreign_currency_code: "USD",
          foreign_currency_symbol: "$",
          foreign_currency_decimal_places: 2,
          amount: "123.45",
          foreign_amount: "123.45",
          description: "Vegetables",
          source_id: "2",
          source_name: "Checking account",
          source_iban: "NL02ABNA0123456789",
          source_type: "Asset account",
          destination_id: "2",
          destination_name: "Buy and Large",
          destination_iban: "NL02ABNA0123456789",
          destination_type: "Asset account",
          budget_id: "4",
          budget_name: "Groceries",
          category_id: "43",
          category_name: "Groceries",
          bill_id: "111",
          bill_name: "Monthly rent",
          reconciled: false,
          notes: "Some example notes",
          tags: null,
          internal_reference: "string",
          external_id: "string",
          external_url: "string",
          original_source: "string",
          recurrence_id: 0,
          recurrence_total: 0,
          recurrence_count: 12,
          bunq_payment_id: "string",
          import_hash_v2: "string",
          sepa_cc: "string",
          sepa_ct_op: "string",
          sepa_ct_id: "string",
          sepa_db: "string",
          sepa_country: "string",
          sepa_ep: "string",
          sepa_ci: "string",
          sepa_batch_id: "string",
          interest_date: "2022-08-14T18:14:41.579Z",
          book_date: "2022-08-14T18:14:41.579Z",
          process_date: "2022-08-14T18:14:41.579Z",
          due_date: "2022-08-14T18:14:41.579Z",
          payment_date: "2022-08-14T18:14:41.579Z",
          invoice_date: "2022-08-14T18:14:41.579Z",
          latitude: 51.983333,
          longitude: 5.916667,
          zoom_level: 6,
          has_attachments: false,
        },
      ],
    },
    links: {
      "0": {
        rel: "self",
        uri: "/OBJECTS/1",
      },
      self: "https://demo.firefly-iii.org/api/v1/OBJECTS/1",
    },
  },
] as Transaction[];
